version: '3.8'
services:
  backend:
    container_name: main-backend-1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://tawsif:123@main_db:5432/main
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=tawsif
      - RABBITMQ_PASSWORD=123
    ports: 
       - 8002:8000
    volumes:
       - .:/app
    networks:
      - main_network
      - rabbitmq_network
    depends_on:
      - main_db
  main_db:
    image: postgres:latest
    container_name: main_db
    restart: always
    environment:
      - POSTGRES_USER=tawsif
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=main
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - main_network
    

networks:
  main_network:
    driver: bridge
  rabbitmq_network:
    external: true